# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:

        edit_preview:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true

        square_xl:
            quality: 75
            filters:
                thumbnail:
                    size: [400, 400]
                    mode: outbound
                    allow_upscale: true

        square_md:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true

